apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: YOUR_PVC_NAME
  labels:
    app: YOUR_LABEL_OF_PVC_NAME
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: default
